### ISSUE TITLE
bug: UI bugs is every page

### ISSUE THREAD

**Issue by ruru-m07** [vercel-labs/app-router-auth#4]
i think this project is not complete or no one need to complete this. 

![image](https://github.com/vercel-labs/app-router-auth/assets/142723369/5cd0fcf8-0ee4-4dc0-86b2-d21aec3c1010)

![image](https://github.com/vercel-labs/app-router-auth/assets/142723369/78b6c286-7112-4a47-bf3a-b39bfde3ed6c)

![image](https://github.com/vercel-labs/app-router-auth/assets/142723369/366ea2f6-9271-48e0-a902-8deeaf266ad8)

is this project is open to fix issue or now this project is close?

**Comment by delbaoliveira** [comment]
Thanks for raising @ruru-m07. These are dark class variants from Shadcn UI components, looks like your system preference is set to dark. I'll remove it so we don't have to make a dark mode version.
